[build]
  command = "# no build command"
  functions = "api/routes"
  publish = "public"

[[redirects]]
  from = "/api/stripe/portal-url"
  to = "/.netlify/functions/stripe_portal-url"
  status = 200
  force = true

[[redirects]]
  from = "/api/stripe/subscription"
  to = "/.netlify/functions/stripe_subscription"
  status = 200
  force = true
